"""empty message

Revision ID: 67ef2386b5c3
Revises: 
Create Date: 2026-10-02 14:55:29.767478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ef2386b5c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('custom_harbor_url', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('environments_site_code_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('environments_site_code_key'), ['site_code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('custom_harbor_url')
        batch_op.drop_column('custom_name')

    # ### end Alembic commands ###
