"""Update environments schema

Revision ID: 91c11d7c8084
Revises: c1cde9c26a88
Create Date: 2026-10-05 15:39:51.164982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c11d7c8084'
down_revision = 'c1cde9c26a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ntp_server', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_pod_cidr', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_service_cidr', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_vkr_version', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_cp_nodes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k8s_worker_nodes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k8s_storage_class', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_cp_vm_class', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('k8s_worker_vm_class', sa.String(length=255), nullable=True))
        batch_op.drop_column('k8s_control_plane_replicas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k8s_control_plane_replicas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('k8s_worker_vm_class')
        batch_op.drop_column('k8s_cp_vm_class')
        batch_op.drop_column('k8s_storage_class')
        batch_op.drop_column('k8s_worker_nodes')
        batch_op.drop_column('k8s_cp_nodes')
        batch_op.drop_column('k8s_vkr_version')
        batch_op.drop_column('k8s_service_cidr')
        batch_op.drop_column('k8s_pod_cidr')
        batch_op.drop_column('ntp_server')

    # ### end Alembic commands ###
