"""Update environments schema

Revision ID: c1cde9c26a88
Revises: fd9fbf68fdd6
Create Date: 2026-10-05 14:52:41.832104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cde9c26a88'
down_revision = 'fd9fbf68fdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k8s_control_plane_replicas', sa.Integer(), nullable=True))
        batch_op.drop_column('custom_name')
        batch_op.drop_column('custom_harbor_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_harbor_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('k8s_control_plane_replicas')

    # ### end Alembic commands ###
