"""Update environments schema

Revision ID: fd9fbf68fdd6
Revises: 67ef2386b5c3
Create Date: 2026-10-02 15:34:43.204022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9fbf68fdd6'
down_revision = '67ef2386b5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ca_crt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('k8s_namespace', sa.String(length=100), server_default='ges-namespace', nullable=True))
        batch_op.add_column(sa.Column('k8s_cluster', sa.String(length=100), server_default='ges-cluster', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_column('k8s_cluster')
        batch_op.drop_column('k8s_namespace')
        batch_op.drop_column('ca_crt')

    # ### end Alembic commands ###
